/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.sangjinshin.cs378.assign5;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CabStyle { 
  Crew, Extended, Regular  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CabStyle\",\"namespace\":\"com.sangjinshin.cs378.assign5\",\"symbols\":[\"Crew\",\"Extended\",\"Regular\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
