/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.sangjinshin.cs378.assign5;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Condition { 
  New, Used  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Condition\",\"namespace\":\"com.sangjinshin.cs378.assign5\",\"symbols\":[\"New\",\"Used\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
